trigger:
- master
- develop

resources:
- repo: self

variables:
  imageName: 'projectorigin/account-service'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  tag: '$(Build.BuildId)'
  ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
  tag: 'dev_$(Date:yyyyMMdd)$(Rev:.r)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: build_and_publish
  displayName: Build and publish
  jobs:  
  - job: docker_build_push
    displayName: Docker build and push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        command: build
        repository: $(imageName)
        Dockerfile: Dockerfile
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: dockerHub
        tags: |
          $(tag)