trigger:
  branches:
    include:
    - '*'

pr:
  - '*'

resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      endpoint: project-origin
      name: project-origin/pipeline-templates

variables:
- name: releaseName
  value: 'account-service'
- name: imageName
  value: 'projectorigin/$(releaseName)'
- template: vars.yml@templates

pool:
  vmImage: 'ubuntu-latest'

jobs:
    - template: job-run-pytest.yml@templates
  
  - ${{ if nq(variables['Build.Reason'], 'PullRequest') }}:
    - template: job-docker-build.yml@templates
      parameters:
        imageName: $(imageName)
        tag: $(tag)

  - ${{ if nq(variables['Build.Reason'], 'PullRequest') }}:
    - template: job-deploy.yml@templates
      parameters:
        kubeCon: $(kubeCon)
        namespace: $(namespace)
        releaseName: $(releaseName)
        deploymentEnvironment: $(deploymentEnvironment)
        overrideValues: tag=$(tag)
        pool:
          ${{ if ne(variables['poolName'], '') }}:
            name: $(poolName)
          ${{ if eq(variables['poolName'], '') }}:
            vmImage: 'ubuntu-latest'