trigger:
  branches:
    include:
    - master
    - test
    - develop

# no PR triggers
pr: none

resources:
- repo: self

variables:
  imageName: 'projectorigin/account-service'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    kubeCon: 'kubecon-eloprindelse-prod'
    namespace: 'eloprindelse'
    tag: '$(Build.BuildId)\nlatest'
  ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
    kubeCon: 'test-kube-con'
    namespace: 'test-project-origin'
    tag: 'test.$(Build.BuildId)'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    kubeCon: 'dev-kube-con'
    namespace: 'dev-project-origin'
    tag: 'canary\nlatest'

jobs:  
  - job: build_deploy
    displayName: Build and Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Docker@2
        displayName: Build docker image
        inputs:
          command: build
          repository: $(imageName)
          Dockerfile: Dockerfile
          tags: |
            $(tag)

      - task: Docker@2
        displayName: Push image
        inputs:
          command: push
          repository: $(imageName)
          containerRegistry: dockerHub
          tags: |
            $(tag)

      - task: HelmDeploy@0
        displayName: Helm upgrade
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: $(kubeCon)
          namespace: $(namespace)
          command: upgrade
          chartType: filepath
          chartPath: ./chart
          releaseName: account-service
          overrideValues: tag=$(tag)
          install: true
          waitForExecution: true