
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-deployment
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: account-service-api-container
          image: projectorigin/account-service:{{ .Values.tag }}
          ports:
            - containerPort: 8085

          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: account-config
            - secretRef:
                name: account-system-secret
            - secretRef:
                name: account-hydra-secret
            - secretRef:
                name: account-db-secret
            - secretRef:
                name: account-webhook-secret
          env:
            - name: SERVICE_NAME
              value: AccountService
            - name: WORKERS
              value: "{{ .Values.workers }}"
            - name: WORKER_CONNECTIONS
              value: "{{ .Values.workerconnections }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-beat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-beat-deployment
  template:
    metadata:
      labels:
        app: account-beat-deployment
    spec:
      containers:
        - name: account-service-api-container
          image: projectorigin/account-service:{{ .Values.tag }}
          args: ["./entrypoint.beat.sh"]
          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: account-config
            - secretRef:
                name: account-system-secret
            - secretRef:
                name: account-hydra-secret
            - secretRef:
                name: account-db-secret
            - secretRef:
                name: account-webhook-secret
          env:
            - name: SERVICE_NAME
              value: AccountServiceBeat

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-worker-deployment
  template:
    metadata:
      labels:
        app: account-worker-deployment
    spec:
      containers:
        - name: account-service-api-container
          image: projectorigin/account-service:{{ .Values.tag }}
          args: ["./entrypoint.worker.sh"]
          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: account-config
            - secretRef:
                name: account-system-secret
            - secretRef:
                name: account-hydra-secret
            - secretRef:
                name: account-db-secret
            - secretRef:
                name: account-webhook-secret
          env:
            - name: SERVICE_NAME
              value: AccountServiceWorker
            - name: CONCURRENCY
              value: "{{ .Values.concurrency }}"
