"""empty message

Revision ID: 1a4910ee7958
Revises: 1961d4778ef8
Create Date: 2020-07-07 14:10:55.852304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a4910ee7958'
down_revision = 'b86b0214ee50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ggo_ggo', sa.Column('emissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ggo_ggo', 'emissions')
    # ### end Alembic commands ###
