"""empty message

Revision ID: 9968d3a3fcfb
Revises: f737261d71c2
Create Date: 2020-06-04 08:39:29.769489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9968d3a3fcfb'
down_revision = 'f737261d71c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        WITH existing AS (
          DELETE FROM accounts_meteringpoint_index_sequence AS s
          RETURNING user_id, (SELECT max(index) FROM accounts_meteringpoint_index_sequence WHERE user_id = s.user_id) AS index
        )
        INSERT INTO accounts_meteringpoint_index_sequence (user_id, index)
        SELECT DISTINCT ON (user_id) user_id, index FROM existing;
    """)
    op.drop_constraint('accounts_meteringpoint_index_sequence_user_id_index_key', 'accounts_meteringpoint_index_sequence', type_='unique')
    op.create_unique_constraint(None, 'accounts_meteringpoint_index_sequence', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts_meteringpoint_index_sequence', type_='unique')
    op.create_unique_constraint('accounts_meteringpoint_index_sequence_user_id_index_key', 'accounts_meteringpoint_index_sequence', ['user_id', 'index'])
    # ### end Alembic commands ###
