"""empty message

Revision ID: ba2bf30e72b2
Revises: 
Create Date: 2020-04-23 18:28:38.815215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2bf30e72b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('master_extended_key', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expire', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_sub'), 'auth_user', ['sub'], unique=True)
    op.create_table('webhook_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Enum('ON_GGO_RECEIVED', name='event'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscription_event'), 'webhook_subscription', ['event'], unique=False)
    op.create_index(op.f('ix_webhook_subscription_id'), 'webhook_subscription', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_subscription_subject'), 'webhook_subscription', ['subject'], unique=False)
    op.create_table('accounts_meteringpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('key_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key_index')
    )
    op.create_index(op.f('ix_accounts_meteringpoint_gsrn'), 'accounts_meteringpoint', ['gsrn'], unique=True)
    op.create_index(op.f('ix_accounts_meteringpoint_id'), 'accounts_meteringpoint', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_meteringpoint_user_id'), 'accounts_meteringpoint', ['user_id'], unique=False)
    op.create_table('accounts_meteringpoint_index_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'index')
    )
    op.create_index(op.f('ix_accounts_meteringpoint_index_sequence_id'), 'accounts_meteringpoint_index_sequence', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_meteringpoint_index_sequence_user_id'), 'accounts_meteringpoint_index_sequence', ['user_id'], unique=False)
    op.create_table('ggo_ggo_index_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'index')
    )
    op.create_index(op.f('ix_ggo_ggo_index_sequence_id'), 'ggo_ggo_index_sequence', ['id'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_index_sequence_user_id'), 'ggo_ggo_index_sequence', ['user_id'], unique=False)
    op.create_table('ledger_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'SUBMITTED', 'DECLINED', 'COMPLETED', name='batchstate'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('poll_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_batch_id'), 'ledger_batch', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_batch_user_id'), 'ledger_batch', ['user_id'], unique=False)
    op.create_table('ggo_ggo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('key_index', sa.Integer(), nullable=True),
    sa.Column('issue_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('technology_code', sa.String(), nullable=False),
    sa.Column('fuel_code', sa.String(), nullable=False),
    sa.Column('issued', sa.Boolean(), nullable=False),
    sa.Column('stored', sa.Boolean(), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('synchronized', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('issue_gsrn', sa.String(), nullable=True),
    sa.Column('retire_gsrn', sa.String(), nullable=True),
    sa.Column('retire_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['issue_gsrn'], ['accounts_meteringpoint.gsrn'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ggo_ggo.id'], ),
    sa.ForeignKeyConstraint(['retire_gsrn'], ['accounts_meteringpoint.gsrn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_ggo_ggo_address'), 'ggo_ggo', ['address'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_begin'), 'ggo_ggo', ['begin'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_expire_time'), 'ggo_ggo', ['expire_time'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_fuel_code'), 'ggo_ggo', ['fuel_code'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_id'), 'ggo_ggo', ['id'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_issue_gsrn'), 'ggo_ggo', ['issue_gsrn'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_issue_time'), 'ggo_ggo', ['issue_time'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_issued'), 'ggo_ggo', ['issued'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_locked'), 'ggo_ggo', ['locked'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_parent_id'), 'ggo_ggo', ['parent_id'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_retire_address'), 'ggo_ggo', ['retire_address'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_retire_gsrn'), 'ggo_ggo', ['retire_gsrn'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_retired'), 'ggo_ggo', ['retired'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_sector'), 'ggo_ggo', ['sector'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_stored'), 'ggo_ggo', ['stored'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_synchronized'), 'ggo_ggo', ['synchronized'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_technology_code'), 'ggo_ggo', ['technology_code'], unique=False)
    op.create_index(op.f('ix_ggo_ggo_user_id'), 'ggo_ggo', ['user_id'], unique=False)
    op.create_table('ledger_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('parent_ggo_id', sa.Integer(), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('meteringpoint_id', sa.Integer(), nullable=True),
    sa.Column('measurement_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['ledger_batch.id'], ),
    sa.ForeignKeyConstraint(['meteringpoint_id'], ['accounts_meteringpoint.id'], ),
    sa.ForeignKeyConstraint(['parent_ggo_id'], ['ggo_ggo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'order'),
    sa.UniqueConstraint('parent_ggo_id')
    )
    op.create_index(op.f('ix_ledger_transaction_batch_id'), 'ledger_transaction', ['batch_id'], unique=False)
    op.create_index(op.f('ix_ledger_transaction_id'), 'ledger_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_transaction_parent_ggo_id'), 'ledger_transaction', ['parent_ggo_id'], unique=False)
    op.create_table('ledger_split_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('ggo_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ggo_id'], ['ggo_ggo.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ggo_id')
    )
    op.create_index(op.f('ix_ledger_split_target_ggo_id'), 'ledger_split_target', ['ggo_id'], unique=False)
    op.create_index(op.f('ix_ledger_split_target_id'), 'ledger_split_target', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_split_target_reference'), 'ledger_split_target', ['reference'], unique=False)
    op.create_index(op.f('ix_ledger_split_target_transaction_id'), 'ledger_split_target', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_split_target_transaction_id'), table_name='ledger_split_target')
    op.drop_index(op.f('ix_ledger_split_target_reference'), table_name='ledger_split_target')
    op.drop_index(op.f('ix_ledger_split_target_id'), table_name='ledger_split_target')
    op.drop_index(op.f('ix_ledger_split_target_ggo_id'), table_name='ledger_split_target')
    op.drop_table('ledger_split_target')
    op.drop_index(op.f('ix_ledger_transaction_parent_ggo_id'), table_name='ledger_transaction')
    op.drop_index(op.f('ix_ledger_transaction_id'), table_name='ledger_transaction')
    op.drop_index(op.f('ix_ledger_transaction_batch_id'), table_name='ledger_transaction')
    op.drop_table('ledger_transaction')
    op.drop_index(op.f('ix_ggo_ggo_user_id'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_technology_code'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_synchronized'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_stored'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_sector'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_retired'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_retire_gsrn'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_retire_address'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_parent_id'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_locked'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_issued'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_issue_time'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_issue_gsrn'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_id'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_fuel_code'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_expire_time'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_begin'), table_name='ggo_ggo')
    op.drop_index(op.f('ix_ggo_ggo_address'), table_name='ggo_ggo')
    op.drop_table('ggo_ggo')
    op.drop_index(op.f('ix_ledger_batch_user_id'), table_name='ledger_batch')
    op.drop_index(op.f('ix_ledger_batch_id'), table_name='ledger_batch')
    op.drop_table('ledger_batch')
    op.drop_index(op.f('ix_ggo_ggo_index_sequence_user_id'), table_name='ggo_ggo_index_sequence')
    op.drop_index(op.f('ix_ggo_ggo_index_sequence_id'), table_name='ggo_ggo_index_sequence')
    op.drop_table('ggo_ggo_index_sequence')
    op.drop_index(op.f('ix_accounts_meteringpoint_index_sequence_user_id'), table_name='accounts_meteringpoint_index_sequence')
    op.drop_index(op.f('ix_accounts_meteringpoint_index_sequence_id'), table_name='accounts_meteringpoint_index_sequence')
    op.drop_table('accounts_meteringpoint_index_sequence')
    op.drop_index(op.f('ix_accounts_meteringpoint_user_id'), table_name='accounts_meteringpoint')
    op.drop_index(op.f('ix_accounts_meteringpoint_id'), table_name='accounts_meteringpoint')
    op.drop_index(op.f('ix_accounts_meteringpoint_gsrn'), table_name='accounts_meteringpoint')
    op.drop_table('accounts_meteringpoint')
    op.drop_index(op.f('ix_webhook_subscription_subject'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_id'), table_name='webhook_subscription')
    op.drop_index(op.f('ix_webhook_subscription_event'), table_name='webhook_subscription')
    op.drop_table('webhook_subscription')
    op.drop_index(op.f('ix_auth_user_sub'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
