"""empty message

Revision ID: d3f593e661a8
Revises: 9968d3a3fcfb
Create Date: 2020-06-10 10:49:24.691569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f593e661a8'
down_revision = '9968d3a3fcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accounts_meteringpoint', ['gsrn'])
    op.create_unique_constraint(None, 'webhook_subscription', ['subject', 'event', 'url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_subscription', type_='unique')
    op.drop_constraint(None, 'accounts_meteringpoint', type_='unique')
    # ### end Alembic commands ###
