"""empty message

Revision ID: dd6130a7a463
Revises: 1a4910ee7958
Create Date: 2020-09-22 14:43:24.519050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6130a7a463'
down_revision = '1a4910ee7958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE auth_user SET active='t';")
    op.alter_column('auth_user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'active')
    # ### end Alembic commands ###
