"""empty message

Revision ID: e46a7069249a
Revises: b79e0e63d5b4
Create Date: 2020-05-25 13:25:59.194225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46a7069249a'
down_revision = 'b79e0e63d5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_batch', sa.Column('submitted', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger_batch', 'submitted')
    # ### end Alembic commands ###
