"""empty message

Revision ID: f737261d71c2
Revises: f59f7f2e5ef1
Create Date: 2020-06-04 08:22:33.052033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f737261d71c2'
down_revision = 'f59f7f2e5ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        WITH existing AS (
          DELETE FROM ggo_ggo_index_sequence AS s
          RETURNING user_id, (SELECT max(index) FROM ggo_ggo_index_sequence WHERE user_id = s.user_id) AS index
        )
        INSERT INTO ggo_ggo_index_sequence (user_id, index)
        SELECT DISTINCT ON (user_id) user_id, index FROM existing;
    """)
    op.create_unique_constraint(None, 'ggo_ggo', ['user_id', 'key_index'])
    op.drop_constraint('ggo_ggo_index_sequence_user_id_index_key', 'ggo_ggo_index_sequence', type_='unique')
    op.create_unique_constraint(None, 'ggo_ggo_index_sequence', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ggo_ggo_index_sequence', type_='unique')
    op.create_unique_constraint('ggo_ggo_index_sequence_user_id_index_key', 'ggo_ggo_index_sequence', ['user_id', 'index'])
    op.drop_constraint(None, 'ggo_ggo', type_='unique')
    # ### end Alembic commands ###
